Added ogr functions. Basic usage example.
ddohler/gdal-js pull request #39
Opened 2021-09-24 06:37 UTC by callmeahab

@ddohler I added most of the OGR functions for my use case, and created a sample worker.

However I'm stuck with one issue and would like your opinion on it. `OGR_G_ExportToJson` function always returns `"{ \"type\": \"Unknown\", \"coordinates\": null }"`, even though reading geometry with `OGR_G_GetX` works fine, perhaps I did the function binding wrong on the js side.

Also let me know if something else needs to be fixed.

2021-09-24 06:39 UTC, callmeahab commented
I also may have left some comments about tiff in the example since I used it as a template for gdb worker. :)

2021-09-24 11:16 UTC, callmeahab commented
Just realised I need to pass actual geometry to `OGR_G_ExportToJson` instead of the pointer to geometry. I'll look into fixing that.

2021-09-24 12:48 UTC, ddohler commented
@callmeahab Thanks a ton, this looks great -- I agree about the issue with `OGR_G_ExportToJson`, it looks like it needs a pointer of type `OGRGeometryH` rather than an `OGRFeatureH`. Let me know once you've got that sorted and I'll review.

2021-09-24 13:51 UTC, callmeahab commented
But `OGR_F_GetGeometryRef` does seem to return `OGRGeometryH`, I might be misunderstanding something here.

2021-09-24 14:37 UTC, ddohler commented
Oh, hmm, I missed that you were calling `OGR_F_GetGeometryRef` first, so now I'm not sure what's happening, this looks right, and the function bindings look right too. Is the pointer returned from `OGR_F_GetGeometryRef` non-zero? Can you pass it to other `OGR_G_*` methods successfully?

2021-09-24 14:57 UTC, callmeahab commented
Yeah, `OGR_F_GetGeometryRef` does return a pointer and `OGR_G_GetX` and `OGR_G_GetY` work fine.

2021-09-24 16:03 UTC, callmeahab commented
Only thing that comes to mind is that geometry I'm testing with is `wkbPointZM`, so I might need to flatten it before using it. Is there a way to compile a macro like `wkbFlatten`?

2021-09-24 16:30 UTC, ddohler commented
Hm, that could be it -- could you try with a different geometry to confirm? Emscripten can compile macros, but to my knowledge it doesn't compile them into freestanding Javascript functions, so it would have to be used somewhere in order to get compiled as a function. It looks like `OGR_G_FlattenTo2D` might do something what's needed? But I'm not really familiar with this area of GDAL.

2021-09-24 17:02 UTC, callmeahab commented
@ddohler Thanks, I'll give it a shot.

2021-09-27 07:06 UTC, callmeahab commented
I get `shared:WARNING: undefined exported function: "_OGR_G_FlattenTo2D, '_OGR_G_FlattenTo2D,' '_OGR_G_ExportToGML"` when I try compiling, perhaps we need a newer version of GDAL?

2021-09-27 12:07 UTC, callmeahab commented
Upgrading GDAL to 2.4 fixed the original issue without the need to flatten the geometry. I also tried upgrading to 3.x version but I'm not skilled enough to figure out what needs to change in the build process, even though it just seems like we just need to install some dependencies in the Docker image.

2021-09-27 12:09 UTC, callmeahab commented
`gdal.wasm` file size has is now 7.8 mb

2021-10-01 20:09 UTC, ddohler commented
Sorry for the delay in testing this -- I just wanted to drop in a note to say that I'm hoping to get to this during the second half of next week. Thanks for your patience!

2021-10-02 12:45 UTC, callmeahab commented
No worries, I'm still working through all of my use cases trying to find all the functions I need to include in the build.

2021-10-04 05:08 UTC, callmeahab commented
I actually ran across a use case where GDAL 3.1 is required. When I try to reproject geometry, this seems to be the function: https://gdal.org/api/vector_c_api.html?highlight=ogr_g#_CPPv426OGR_GeomTransformer_Create28OGRCoordinateTransformationH12CSLConstList, however its on't available in version 3.1.

2021-10-15 21:33 UTC, ddohler commented
Just wanted to let you know that I haven't forgotten about this! I'm partway through reviewing and I will try to really hard to finish up next week.

2021-10-18 16:53 UTC, ddohler requested changes
Thanks again for putting this together, this is a really great start! I've left some smaller comments in the source, but at a high level, here's how I'd like to proceed with this: I'm hoping that we can achieve the capabilities you need while remaining with GDAL 2.1. I would love to upgrade because 2.1 is now getting quite old, but a GDAL version upgrade would require much more in-depth testing on my part, which would make this take even longer than it already has.

I reviewed the GDAL API and I left a suggestion for how it might be possible to export XYZM geometries to GeoJSON without upgrading GDAL -- can you give that a try and let me know if it works, or point me to some sample data I could use to test myself?

I'm also hopeful that reprojecting geometries can be done without upgrading; I've successfully warped images and reprojected sequences of coordinates under 2.1, so I think it should be possible to reproject geometries as well.

Here's what I would try first to reproject geometries, which is similar to the process for an array of points. Can you let me know if this doesn't work for you? I haven't tested it so it might not be exactly right but it should be close:

```javascript
// OSRNewSpatialReference is already exported in gdal-js; srcCRSStr and destCRSStr need 
// to be WKT strings defining the source and destination coordinate reference systems.
const sourceSrs = OSRNewSpatialReference(srcCRSStr);
const targetSrs = OSRNewSpatialReference(destCRSStr);
// OCTNewCoordinateTransformation and OGRCreateCoordinateTransformation are the same as per the docs:
// https://gdal.org/api/ogrspatialref.html#ogr__spatialref_8h_1ac4bb7940fbb8882d261fee06becb3a81
// And OCTNewCoordinateTransformation is already available in gdal-js.
// If this doesn't work I would try replacing with OGRCreateCoordinateTransformation
const coordTransform = OCTNewCoordinateTransformation(sourceSrs, targetSrs);
// Transform geometry in-place. Assumes the geometry exists
OGR_G_Transform(geometry, coordTransform)
```

Here's an example of this process happening in Loam (but for arrays of coordinates, not geometries): https://github.com/azavea/loam/blob/master/src/wrappers/reproject.js

Can you give this a try (if you haven't already) and let me know if it works?

Thanks a lot for your hard work on this!

2021-10-18 16:53 UTC, ddohler commented on Makefile
> +  '_OGR_G_ExportToWkt'\
These should be added to the project README as well.

2021-10-18 16:53 UTC, ddohler commented on examples/inspect_gdb/README
> +directory. There are some symlinks provided that will do this automatically if
This should include symlinks to `gdal.js`, `gdal.wasm`, and `gdal.data` in `examples/inspect_gdb/` so that the example will work once the project is compiled.

2021-10-18 16:53 UTC, ddohler commented on examples/inspect_gdb/index.html
> +    <input type="file" id="gdb-select">
Adding `multiple="true"` here will allow this to be used for unzipped multi-file formats like Shapefiles as well (tested locally).

2021-10-18 16:53 UTC, ddohler commented on examples/inspect_gdb/worker.js
> +                var geometry = OGR_F_GetGeometryRef(feature);
Could you try adding 
```javascript
OGR_G_Set3D(geometry, false);
OGR_G_SetMeasured(geometry, false);
```
here (before the call to `OGR_G_ExportToJson`) and let me know if that resolves the issue with exporting to JSON for you under GDAL 2.1?

I don't have an XYZM data source handy, so if you've got some sample data you could direct me to, I'd also be happy to experiment myself.

2021-10-18 18:08 UTC, callmeahab commented
> Here's what I would try first to reproject geometries, which is similar to the process for an array of points. Can you let me know if this doesn't work for you? I haven't tested it so it might not be exactly right but it should be close:
> 
> ```js
> // OSRNewSpatialReference is already exported in gdal-js; srcCRSStr and destCRSStr need 
> // to be WKT strings defining the source and destination coordinate reference systems.
> const sourceSrs = OSRNewSpatialReference(srcCRSStr);
> const targetSrs = OSRNewSpatialReference(destCRSStr);
> // OCTNewCoordinateTransformation and OGRCreateCoordinateTransformation are the same as per the docs:
> // https://gdal.org/api/ogrspatialref.html#ogr__spatialref_8h_1ac4bb7940fbb8882d261fee06becb3a81
> // And OCTNewCoordinateTransformation is already available in gdal-js.
> // If this doesn't work I would try replacing with OGRCreateCoordinateTransformation
> const coordTransform = OCTNewCoordinateTransformation(sourceSrs, targetSrs);
> // Transform geometry in-place. Assumes the geometry exists
> OGR_G_Transform(geometry, coordTransform)
> ```
> 
> Here's an example of this process happening in Loam (but for arrays of coordinates, not geometries): https://github.com/azavea/loam/blob/master/src/wrappers/reproject.js
> 
> Can you give this a try (if you haven't already) and let me know if it works?
> 
> Thanks a lot for your hard work on this!

Thanks for reviewing. It was couple of weeks ago so my memory might be hazy but I believe I tried this approach and it didn't work. I didn't push that code in example because it didn't reproject successfully.

2021-10-18 18:09 UTC, callmeahab commented on examples/inspect_gdb/worker.js
> +                var geometry = OGR_F_GetGeometryRef(feature);
I have 3d geometry to test this with, however I'd also like to support 2d geometry, can we instead keep the upgraded version?

2021-10-18 19:40 UTC, ddohler commented
Darn, that's unfortunate. Do you have any ability to provide sample data or a more detailed description of what you're trying to do and what results you expect? Thanks!

2022-08-14 18:18 UTC, ddohler commented
@callmeahab Sorry for the very long delay here! I have had a block of free time to work on this and I've made significant progress. I did my own upgrade to GDAL 2.4 because I also upgraded to the latest version of Emscripten, which required some additional changes to the build process. After that, I added a few more functions to resolve #33 . I am recompiling now and will test everything tomorrow. Assuming everything looks good, I'll merge this and cut a release this week. This is the last in a long line of commits to get both Emscripten and GDAL upgraded to support GDAL 2.4, so I am going to force-push here to use this PR for all of that functionality.

I assume you've moved onto other things by now, but in any case, thank you very much for your help -- your example program reduced the development time for this significantly!

2022-08-15 06:30 UTC, milosimr commented
@ddohler Great to hear. Glad to hear you found it useful.

2022-08-15 06:34 UTC, callmeahab commented
@ddohler Great to hear! Glad you found it useful!

2022-08-15 06:49 UTC, ddohler commented
I ended up having to open a separate PR; the changes from this branch are merged in #41, so I'm closing this. Thanks again!

2022-08-15 06:49 UTC, closed without merging